# Generated by Django 4.1.7 on 2023-03-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandprofile',
            options={'permissions': (('dashboard', 'access band dashboard'),)},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='time'),
        ),
    ]
