# Generated by Django 4.1.7 on 2023-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_bandprofile_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
