# Generated by Django 4.1.7 on 2023-03-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_bandprofile_genre_remove_venueprofile_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='bands',
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.genre'),
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='moods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.mood'),
        ),
    ]
