# Generated by Django 4.1.7 on 2023-03-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_genre_bands_remove_mood_bands_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mood',
            old_name='genre_name',
            new_name='name',
        ),
    ]
