# Generated by Django 4.1.7 on 2023-03-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_event_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandprofile',
            options={},
        ),
        migrations.AddField(
            model_name='venueprofile',
            name='moods',
            field=models.ManyToManyField(to='main_app.mood'),
        ),
    ]
