# Generated by Django 4.1.7 on 2023-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_genre_name_genre_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandprofile',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='bandprofile',
            name='moods',
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.genre'),
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='moods',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.mood'),
        ),
    ]
