# Generated by Django 4.1.7 on 2023-03-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_bandprofile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandprofile',
            name='genres',
            field=models.ManyToManyField(to='main_app.genre'),
        ),
        migrations.AlterField(
            model_name='bandprofile',
            name='moods',
            field=models.ManyToManyField(to='main_app.mood'),
        ),
    ]
